# Style and colors generated for the jan theme.

[global]
origin = top-right
offset = (20, 60)

transparency = 8
corner_radius = 0

frame_width = 2
frame_color = "#6800d2"

font = Inconsolata Semi Condensed Extra Bold 9
icon_theme = "BeautyLine, Adwaita""

format = "<span size='xx-large' font_desc='Cantarell 9' weight='bold' foreground='#19bffe'>%s</span>\n%b"

[urgency_low]
timeout = 3
background = "#070219"
foreground = "#a6e22e"

[urgency_normal]
timeout = 5
background = "#070219"
foreground = "#27fbfe"

[urgency_critical]
timeout = 0
background = "#070219"
foreground = "#fb007a"
